### 1. 导入numpy库并简写为 np

In [2]:
import numpy as np

### 2. 打印numpy的版本和配置说明

In [3]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python\\Library\\include']
blas_opt_inf

### 3.创建一个长度为10的空向量

In [4]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. 如何找到任何一个数组的内存大小？

In [5]:
A = np.zeros((10,10))
print("%d bytes"%(A.size*A.itemsize))#size指数组元素的个数 itemsize指每个元素字节大小
#eg：一个元素类型为float64的数组itemsize属性值为8


800 bytes


### 5. 如何从命令行得到numpy中add函数的说明文档?

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6. 创建一个长度为10并且除了第五个值为1的空向量

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. 创建一个值域范围从10到49的向量

In [8]:
b = np.arange(10,50)#括号后一位不取
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. 反转一个向量(第一个元素变为最后一个）

In [9]:
c = np.arange(10)
c = c[::-1]
print(c)

[9 8 7 6 5 4 3 2 1 0]


### 9. 创建一个 3x3 并且值从0到8的矩阵

In [10]:
a = np.arange(9).reshape(3,3)#np.arange(a,b,c).reshape(m,n):从数字a起，步长为c，
#到b结束，生成m行n列矩阵
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [11]:
q = np.nonzero([1,2,0,0,4,0])
print(q)

(array([0, 1, 4], dtype=int64),)


### 11. 创建一个 3x3 的单位矩阵 

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. 创建一个 3x3x3的随机数组

In [13]:
np.random.random((3,3,3))

array([[[0.58447711, 0.92878601, 0.5080771 ],
        [0.743548  , 0.82298255, 0.92861708],
        [0.16278249, 0.29168461, 0.36911825]],

       [[0.2761701 , 0.50037557, 0.52112717],
        [0.90305777, 0.30244834, 0.52308859],
        [0.74391577, 0.49102679, 0.34806672]],

       [[0.14214503, 0.93352515, 0.45841026],
        [0.54272748, 0.7522809 , 0.19298848],
        [0.04915378, 0.30142151, 0.0114413 ]]])

### 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [14]:
w = np.random.random((10,10))
print(w.max(),w.min())

0.989143183151953 0.012197494561341338


### 14. 创建一个长度为30的随机向量并找到它的平均值

In [15]:
s = np.random.random(30)
print(s.mean())

0.5226778986061313


### 15. 创建一个二维数组，其中边界值为1，其余值为0

In [17]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. 对于一个存在在数组，如何添加一个用0填充的边界?

In [19]:
z = np.ones((5,5))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)#np.pad(array,pad_width,mode,kwargs)array——表示需要填充的数组，
#pad_width——表示每个轴边缘需要填充的数值数目 mode——表示填充的方式

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. 以下表达式运行的结果分别是什么? 
#### (提示: NaN = not a number, inf = infinity)

In [20]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1
print(0 * np.nan,np.nan == np.nan,np.inf > np.nan,np.nan - np.nan,0.3 == 3*0.1)

nan False False nan False


### 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [21]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [23]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [24]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [25]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. 对一个5x5的随机矩阵做归一化

In [26]:
a = np.random.random((5,5))
amax,amin = a.max(),a.min()
a = (a-amin)/(amax-amin)
print(a)

[[0.62415751 0.65184002 0.00278354 0.07550718 0.32555725]
 [0.07629672 0.         0.86591718 0.96437603 0.3995079 ]
 [0.03900839 0.27779555 0.06994688 0.2881109  0.31991422]
 [0.85608109 0.79969225 1.         0.7514628  0.05530716]
 [0.00137902 0.52351079 0.98688834 0.96196634 0.88110044]]


### 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [27]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [28]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [30]:
q = np.arange(11)
q[(3<= q)&(q <= 8)] *= -1
print(q)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


### 26. 下面脚本运行后的结果是什么?
#### print(sum(range(5),-1))
#### from numpy import *
#### print(sum(range(5),-1))

In [31]:
print(sum(range(5),-1))

9


In [32]:
from numpy import *
print(sum(range(5),-1))

10


### 27. 考虑一个整数向量Z,下列表达合法的是哪个? '
#### Z**Z
#### 2 << Z >> 2
#### Z <- Z
#### 1j*Z
#### Z/1/1
#### Z/<Z/>Z 


In [33]:
z = arange(6)
z ** zz =

array([   1,    1,    4,   27,  256, 3125], dtype=int32)

In [35]:
z = arange(6)
2 << z >> 2

array([ 0,  1,  2,  4,  8, 16], dtype=int32)

In [36]:
z = arange(6)
z <- z

array([False, False, False, False, False, False])

In [37]:
z = arange(6)
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j])

In [38]:
z = arange(6)
z/1/1

array([0., 1., 2., 3., 4., 5.])

In [39]:
z = arange(6)
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. 下列表达式的结果分别是什么?
#### np.array(0) / np.array(0)
#### np.array(0) // np.array(0)
#### np.array([np.nan]).astype(int).astype(float)

In [40]:
print(np.array(0) / np.array(0))

nan


D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [42]:
print(np.array(0) // np.array(0))

0


D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [43]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


### 29. 如何从零位对浮点数组做舍入 ?

In [44]:
c = np.random.uniform(-10,+10,10)# np.random.uniform(low上界,high下界,size输出样本数目)
print(np.copysign(np.ceil(np.abs(c)),c))

[-1. -3.  3. -1. -9.  9.  1.  1. -4.  6.]


### 30. 如何找到两个数组中的共同元素? 

In [49]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[5 8]


### 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? 

In [52]:
#Suicide mode on
defaults = np.ones(1) / 0
#Back to sanity
_ = np.seterr(**defaults)
An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
        z = np.ones(1)/0

SyntaxError: invalid syntax (<ipython-input-52-795d9013c52b>, line 5)

### 32. 下面的表达式是正确的吗?
#### np.sqrt(-1) == np.emath.sqrt(-1)

In [53]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [54]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


### 33. 如何得到昨天，今天，明天的日期?

In [59]:
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


### 34. 如何得到所有与2016年7月对应的日期？

In [60]:
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [63]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out=b)

array([3., 3., 3.])

In [64]:
np.divide(a,2,out=a)

array([0.5, 0.5, 0.5])

In [66]:
np.negative(a,out=a)

array([-0.5, -0.5, -0.5])

In [67]:
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

### 36. 用五种不同的方法去提取一个随机数组的整数部分

In [68]:
a = np.random.uniform(0,10,10)
print(a-a%1)

[3. 5. 9. 1. 2. 4. 6. 9. 9. 2.]


In [69]:
print(np.floor(a))

[3. 5. 9. 1. 2. 4. 6. 9. 9. 2.]


In [71]:
print(np.ceil(a)-1)

[3. 5. 9. 1. 2. 4. 6. 9. 9. 2.]


In [72]:
print(a.astype(int))

[3 5 9 1 2 4 6 9 9 2]


In [73]:
print(np.trunc(a))

[3. 5. 9. 1. 2. 4. 6. 9. 9. 2.]


### 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [74]:
s = np.zeros((5,5))
s += np.arange(5)
print(s)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [75]:
def generate():
    for x in range(10):
        yield x
d = np.fromiter(generate(),dtype=float,count=-1)
print(d)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [76]:
f = np.linspace(0,1,11,endpoint=False)[1:]#在0和1之间划分为11份
print(f)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. 创建一个长度为10的随机向量，并将其排序 

In [77]:
a = np.random.random(10)
a.sort()
print(a)

[0.00432771 0.20120981 0.35239415 0.62139573 0.75574909 0.75655292
 0.77385518 0.81144847 0.81946011 0.87655828]


### 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [78]:
a = np.arange(10)
np.add.reduce(a)

45

### 42. 对于两个随机数组A和B，检查它们是否相等

In [79]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


In [80]:
equal2 = np.array_equal(a,b)
print(equal2)

False


### 43. 创建一个只读数组(read-only)

In [81]:
w = np.zeros(10)
w.flags.writeable = False
w[0] = 1

ValueError: assignment destination is read-only

### 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [83]:
a = np.random.random((10,2))
X,Y = a[:,0],a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.13978344 0.61065554 1.08084991 0.95485693 0.28580473 1.1839917
 0.76115681 0.98684398 0.25690354 0.97221779]
[0.56810604 1.04690526 0.99406982 1.00413883 0.69764867 0.99348377
 1.46756622 0.10855677 1.04336359 0.57051575]


### 45. 创建一个长度为10的向量，并将向量中最大值替换为1 

In [85]:
s = np.random.random(10)
s[s.argmax()] = 1
print(s)

[0.28312771 0.07844441 0.37230424 0.34398553 0.79468805 0.71220042
 1.         0.78699473 0.6544614  0.8595857 ]


### 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [97]:
z = np.zeros((5,6),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,6),
                            np.linspace(0,1,5))
print(z)

[[(0. , 0.  ) (0.2, 0.  ) (0.4, 0.  ) (0.6, 0.  ) (0.8, 0.  ) (1. , 0.  )]
 [(0. , 0.25) (0.2, 0.25) (0.4, 0.25) (0.6, 0.25) (0.8, 0.25) (1. , 0.25)]
 [(0. , 0.5 ) (0.2, 0.5 ) (0.4, 0.5 ) (0.6, 0.5 ) (0.8, 0.5 ) (1. , 0.5 )]
 [(0. , 0.75) (0.2, 0.75) (0.4, 0.75) (0.6, 0.75) (0.8, 0.75) (1. , 0.75)]
 [(0. , 1.  ) (0.2, 1.  ) (0.4, 1.  ) (0.6, 1.  ) (0.8, 1.  ) (1. , 1.  )]]


### 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [99]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


### 48. 打印每个numpy标量类型的最小值和最大值？ 

In [100]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. 如何打印一个数组中的所有数值?

In [101]:
np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 50. 给定标量时，如何找到数组中最接近标量的值？

In [103]:
z = np.arange(100)
a = np.random.uniform(0,100)
index = (np.abs(z-a).argmin())
print(z[index])

31
